# https://medium.com/mobileforgood/patterns-for-continuous-integration-with-docker-on-travis-ci-71857fff14c5

# Config
sudo: required

language: node_js

node_js: 10

cache:
  directories: 
    - $HOME/.npm

git:
  submodules: false

services: docker

branches:
  only: master

notifications:
  email: false

# Install
install: . .travis/install/install.sh

# Script
before_script: . .travis/script/before_script.sh
script: . .travis/script/script.sh

# Deploy
deploy: 
  - provider: script
    skip_cleanup: true
    script: . .travis/deploy/deploy.sh

  - provider: releases
    api_key: "$GH_TOKEN"
    skip_cleanup: true
    on:
      condition: "$REQUEST_TYPE == 'release'"

  - provider: script
    skip_cleanup: true
    script: . .travis/deploy/after_deploy.sh
    on:
      condition: "$REQUEST_TYPE == 'release'"