git:
  submodules:
    false

# Add private repo SSH key and then clone submodules.
before_install:
  - echo -e "\n\nmachine github.com\n  $TRAVIS_CI_TOKEN\n" >~/.netrc
  - git submodule update --init --recursive

