# https://medium.com/mobileforgood/patterns-for-continuous-integration-with-docker-on-travis-ci-71857fff14c5
sudo: required

language: node_js

node_js:
  - 10

git:
  submodules: false

services: docker

branches:
  only: master

notifications:
  email: false

install: . .travis/install.sh

before_script: . .travis/before_script.sh

script: . .travis/script.sh

after_script: . .travis/after_script.sh

deploy: 
  provider: script
  skip_cleanup: true
  script: . .travis/deploy.sh