git:
  submodules: false

# Add private repo SSH key and then clone submodules.
before_install:
  - sed -i 's/github/'"$TRAVIS_CI_TOKEN"'@github/g' .gitmodules
  - git submodule update --init --recursive

